app:
  encryption:
    key-base64: MjExZjFiOGQyMWY2NmRmNDkzZTM3MzA1MTExZjFhOTc=

spring:
  application:
    name: payment-application

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
        ddl-auto: none
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            id.db_structure_naming_strategy: legacy
            type_descriptor_sql_type_code: 12
            jdbc.time_zone: UTC

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 30000
        concurrency: 3
        max-concurrency: 10

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true